/// Generate URL strings to contents on different media platforms. These links usually have similar patterns that only differs in terms of content ID, and the functions are here to avoid repetitions and simplifying the writing of these links.
///
/// Note that the generated URLs are of type `string`, not `content`. To make the link clickable you can wrap it with a `link` element, or for more nicely-formatted display text, use functions from `linkify.display` instead.
///
/// Due to privacy reasons, platforms like Xhaohongshu are currently not supported.
/// Please beware the share links generated by these apps contain the sharer's personal info and is thus unsafe. Be cautious not to include them in your writing.
/// If I discover how to generate a sanitized link in the future, I might consider support those platforms.

#import "_impl/url.typ": (
  bili,
  weixin,
  zhihu,
  youtube,
  wiki,
  moegirl,
  twitter,
  isbn,
)

#let B站 = bili
#let 微信 = weixin
#let 知乎 = zhihu
#let 油管 = youtube
#let 维基 = wiki
#let 萌百 = moegirl
#let 推特 = twitter
#let X = twitter